config/routes.rb
Helio::Application.routes.draw do
  ActiveAdmin.routes(self)
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update]
  resources :subscriptions, :only => [:index, :new, :create]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :alert_type
  has_one :agency, :through => :alert_type

  def self.recent(num=5)
  	Subscription.order(:created_at).limit(num)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	before_filter :authenticate_user!

  def index
  	@subscriptions = current_user.subscriptions
  end

  def edit

  end

  def new
  	@alert_types = AlertType.all.collect {|at| at unless Subscription.where(:user=> current_user, :alert_type => at).any? }.compact
  	@subscription = Subscription.new(permitted_params || {})
  end

  def create
  	@subscription = Subscription.new(permitted_params[:subscription])
  	@subscription.user = current_user

  	if @subscription.save
  		redirect_to subscriptions_path, :notice => "You have been subscribed to #{@subscription.alert_type.name}."
  	else
  		render :action => :new
  	end
  end

  def permitted_params
  	params.permit(:subscription => [:alert_type_id])
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.slim
= simple_form_for(@subscription) do |f|

	= f.select :alert_type_id, @alert_types.map {|at| [at.name,at.id]}
	br
	br
	= f.submit "Create Subscription"

app/views/subscriptions/index.html.slim
h1
	| My Subscriptions

p
	= link_to("Add new", new_subscription_path)
	|&nbsp;|&nbsp;
	= link_to("Manage my alert settings in MyUSA", "#{ENV["MYUSA_HOME"]}/settings")
ul
	- if @subscriptions.any?
		- @subscriptions.each do |sub|
			li= sub.alert_type.name + " - " + sub.alert_type.description
	- else
		li
			| You currently have no subscriptions. #{link_to("Add a new subscription", new_subscription_path)} to get started.

app/views/subscriptions/new.html.slim
h1
	| New subscription

- if @alert_types.any?
	= render :partial => 'form'

- else
	p
		= link_to("My Subscriptions", subscriptions_path)
	p
		| Sorry, there are no more alert types for you to subscribe to!