config/routes.rb
Helio::Application.routes.draw do
  ActiveAdmin.routes(self)
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update]
  resources :subscriptions, :only => [:index, :new, :create]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? "success" : "danger"}") 
      button.close aria-hidden="true" data-dismiss="alert" type="button"
      	| &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
        span.sr-only 
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li
	- if user_signed_in?
	  = link_to 'Sign out', signout_path
	- else
	  = link_to 'Sign in', signin_path
- if current_user_is(:admin) or current_user_is(:agency_admin)
	li
		= link_to 'Admin', admin_root_path

app/views/layouts/application.html.slim
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : 'Zombie Alert Notification System'
    meta content=(content_for?(:description) ? yield(:description) : "Zombie Alert Notification System") name="description" 
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body class=("#{controller_name} #{action_name} #{user_signed_in? ? "user-signed-in" : ""}")
    header
      = render 'layouts/navigation'
    main role="main"
      = render 'layouts/messages'
      = yield